# auto_app.py
# Automatically generated by TensorTalezz-RV
from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import pandas as pd

app = FastAPI(title="TensorTalezz-RV Model API")

print("Loading model from test_model.joblib...")
try:
    model = joblib.load("test_model.joblib")
except Exception as e:
    print(f"Error loading model: {e}")
    model = None

class PredictionRequest(BaseModel):
    features: dict  # Pass feature column names as keys

@app.post("/predict")
def predict(req: PredictionRequest):
    if model is None:
        return {"error": "Model not loaded"}
    # Convert JSON dict to single-row dataframe
    df = pd.DataFrame([req.features])
    # Predict
    try:
        from tensor_talezz_rv import predict as tt_predict
        preds = tt_predict(model, df)
        return {"prediction": preds.tolist()}
    except Exception as e:
        return {"error": str(e)}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8080)
