import os
import textwrap
try:
    import joblib
except ImportError:
    pass

def serve_model(model_path="model.joblib", port=8000):
    """
    Generates a lightweight FastAPI/Flask script to serve your model, bridging learning to deployment.
    
    Parameters:
    -----------
    model_path : str
        Path locally where the exported model rests.
    port : int
        The local port to open.
        
    Returns:
    --------
    script_path : str
        The path of the auto-generated api server script.
        
    Example:
    --------
    >>> serve_model("my_exported_model.joblib", port=8080)
    """
    print(f"\n🌍 [Deployment] Generating a simple deployment script for your model...")
    
    app_code = textwrap.dedent(f'''\
    # auto_app.py
    # Automatically generated by TensorTalezz-RV
    from fastapi import FastAPI
    from pydantic import BaseModel
    import joblib
    import pandas as pd
    
    app = FastAPI(title="TensorTalezz-RV Model API")
    
    print("Loading model from {model_path}...")
    try:
        model = joblib.load("{model_path}")
    except Exception as e:
        print(f"Error loading model: {{e}}")
        model = None
        
    class PredictionRequest(BaseModel):
        features: dict  # Pass feature column names as keys
        
    @app.post("/predict")
    def predict(req: PredictionRequest):
        if model is None:
            return {{"error": "Model not loaded"}}
        # Convert JSON dict to single-row dataframe
        df = pd.DataFrame([req.features])
        # Predict
        try:
            from tensor_talezz_rv import predict as tt_predict
            preds = tt_predict(model, df)
            return {{"prediction": preds.tolist()}}
        except Exception as e:
            return {{"error": str(e)}}
            
    if __name__ == "__main__":
        import uvicorn
        uvicorn.run(app, host="0.0.0.0", port={port})
    ''')
    
    script_path = "auto_app.py"
    with open(script_path, "w") as f:
        f.write(app_code)
        
    print(f"✅ Generated '{script_path}'!")
    print(f"   To run this server locally, use the command:")
    print(f"   👉  uvicorn auto_app:app --reload --port {port}\n")
    return script_path


def export_model(model_obj, filepath="model.joblib", format="joblib"):
    """
    Allows saving models in portable formats.
    Currently defaults to joblib, laying groundwork for ONNX.
    
    Example:
    --------
    >>> export_model(model, "my_model.joblib")
    """
    print(f"📦 [Export] Exporting pipeline to {filepath} (format: {format})...")
    if format == "joblib":
        joblib.dump(model_obj, filepath)
        size_kb = os.path.getsize(filepath) / 1024
        print(f"✅ Successfully exported ({size_kb:.1f} KB).")
    else:
        print(f"⚠️ Format '{format}' not fully supported natively yet. Falling back to joblib.")
        joblib.dump(model_obj, f"{filepath}.joblib")
    return filepath


def deploy_edge(model_obj):
    """
    Demonstrates model quantization conceptually or minimally to teach Edge ML.
    """
    print("\n📱 [Edge AI] Preparing model for edge deployment...")
    print("   Applying quantization (simulating float64 -> float16 representation)...")
    print("   Pruning irrelevant ensemble trees to reduce size...")
    # This acts as a wrapper/demo bridging to the lowresource module
    from .lowresource import quantize_model
    # We must extract the base sklearn model from the Pipeline if it's our abstraction
    base_model = model_obj
    if hasattr(model_obj, "pipeline"):
        base_model = model_obj.pipeline.named_steps["model"]
        
    quantized_size = quantize_model(base_model)
    print("✅ Model is now ready for deployment onto embedded devices (IoT, RasPi)!")
    return base_model
